services:

  describer:
    build:
      context: services/describer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 3s
      timeout: 2s
      retries: 4
      start_period: 5s

  web:
    build:
      context: services/web
    depends_on:
      describer:
        condition: service_healthy
    ports:
      - "8080:80"
